<?php

namespace AppBundle\Repository;

/**
 * BarcodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BarcodeRepository extends \Doctrine\ORM\EntityRepository
{
}
