<?php

namespace AppBundle\Repository;

/**
 * MoneyFlowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoneyFlowRepository extends \Doctrine\ORM\EntityRepository
{
}
