<?php

namespace AppBundle\Repository;

/**
 * Order1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOrdersOrderedByDay(){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('DAY(o.createdAt) AS day, MONTH(o.createdAt) AS month, YEAR(o.createdAt) AS year , o')
            ->from('AppBundle:Order', 'o')
            ->groupBy('day, month, year, o');



        $query = $qb->getQuery();

        // On récupère les résultats à partir de la Query
        $results = $query->getResult();

        // On retourne ces résultats
        return $results;
    }
}
