<?php

namespace AppBundle\Repository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAdminPromotion()
    {
        $sql = " 
        SELECT DISTINCT p.user_promotion
        FROM promotions p
        WHERE p.promotion_name = 'admin'
      ";
        $em = $this->getEntityManager();
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute();
        return $stmt->fetch();
    }
    public function getUserPromotion()
    {
        $sql = " 
        SELECT DISTINCT p.user_promotion
        FROM promotions p
        WHERE p.promotion_name = 'simple'
      ";
        $em = $this->getEntityManager();
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute();
        return $stmt->fetch();
    }

}
