<?php

namespace AppBundle\Repository;

/**
 * AuthTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RfidToMatchRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastRfidToMatch($now){

        $sql = " 
        SELECT RTM.id
        FROM rfid_to_match RTM
        WHERE  RTM.createdAt>=\"".date_format($now, 'Y/m/d H:i:s')."\"
        
    ";

        $em = $this->getEntityManager();
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }
}
