<?php

namespace AppBundle\Repository;
use AppBundle\Entity\UserAccount;
/**
 * UserAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatisticRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOrdersOrderedByDay(){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('o')
            ->from('Order', 'o')
            ->orderBy('o.createdAt', 'DESC');


        $query = $qb->getQuery();

        // On récupère les résultats à partir de la Query
        $results = $query->getResult();

        // On retourne ces résultats
        return $results;
    }

}
