<?php

namespace AppBundle\Repository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBarman( ){

        $em =  $this->getEntityManager();
        $query = $em->createQuery(
                "SELECT u
            FROM AppBundle:User u
            WHERE u.role='ROLE_SUPER_ADMIN'");
        return  $query->getSingleResult();
    }

}
