AppBundle\Entity\Promotion:
    exclusion_policy: NONE
    properties:
        id:
            groups: ['user', 'userAccount', 'auth-token','moneyFlow','promotion', 'userLimited']
        userPromotion:
            groups: ['promotion','user']

        promotionName:
            groups: ['promotion']
