AppBundle\Entity\User:
    exclusion_policy: NONE
    properties:
        id:
            groups: ['user', 'userAccount', 'order', 'auth-token','moneyFlow', 'userLimited']

        firstname:
            groups: ['user',  'userLimited']

        lastname:
            groups: ['user','userLimited']

        promotion:
            groups: ['user','userLimited']

        username:
            groups: ['user','userLimited']

        godfather:
            groups: ['user','userLimited']

        nefews:
            groups: ['user']

        email:
            groups: ['user',]

        role:
            groups: ['user','userLimited']

        userAccounts:
            groups: ['user','userLimited']

        moneyLimit:
            groups: ['user','userLimited']

