AppBundle\Entity\UserAccount:
    exclusion_policy: NONE
    properties:
        id:
            groups: ['user','moneyFlow','auth-token','userAccount', 'account','userLimited']

        type:
            groups: ['userAccount',  'account']

        moneyBalance:
            groups: ['userAccount', 'account']

        user:
            groups: ['userAccount']

        orders:
            groups: ['userAccount']

        registerOrders:
            groups: ['userAccount']

        positiveMoneyFlows:
            groups: ['userAccount']

        negativeMoneyFlows:
            groups: ['userAccount']

