AppBundle\Entity\UserAccount:
    exclusion_policy: NONE
    properties:
        id:
            groups: ['user','moneyFlow','auth-token','userAccount', 'account','userLimited','order']

        type:
            groups: ['userAccount', 'user', 'account']

        moneyBalance:
            groups: ['userAccount','user', 'account']

        user:
            groups: ['userAccount','order']

        orders:
            groups: []

        registerOrders:
            groups: []

        positiveMoneyFlows:
            groups: []

        negativeMoneyFlows:
            groups: []

        moneyLimit:
                groups: ['user','account','userAccount']

        creditAllowed:
              groups: ['user','account','userAccount']

        creditToAllowMax:
              groups: ['user','account','userAccount']

    virtual_properties:

        getAvailableBalance:
            groups: ['user','account','userAccount']


