AppBundle\Entity\OrderLine:
    exclusion_policy: NONE
    properties:
        id:
            groups: ['order','orderLine','userAccount']

        quantity:
            groups: ['order' , 'orderLine']

        order:
            groups: ['orderLine']

        product:
            groups: ['order','orderLine']

    virtual_properties:
        getOrderLinePriceAdmin:
            groups: ['order','orderLine']

        getOrderLinePriceUser:
                  groups: ['order','orderLine']

        getOrderLinePriceFinal:
                  groups: ['order','orderLine']






