AppBundle\Entity\ProductCategory:
    exclusion_policy: NONE
    properties:
        id:
            groups: ['product','productCategory','order']

        categoryName:
            groups: ['productCategory','product','order']

        price:
            groups: ['productCategory','product']

        products:
            groups: ['productCategory']


