AppBundle\Entity\AuthToken:
    exclusion_policy: NONE
    properties:
        id:
            groups: ['auth-token']
        value:
            groups: ['auth-token']
        createdAt:
            groups: ['auth-token']
        user:
            groups: ['auth-token']
        isLogWithRfid:
            groups: ['auth-token']


