AppBundle\Entity\OrderLine:
    exclusion_policy: NONE
    properties:
        id:
            groups: ['order','orderLine','userAccount']

        quantity:
            groups: ['order' , 'orderLine']

        order:
            groups: ['orderLine']

        product:
            groups: ['order','orderLine']

        orderLineDuringOrderPrice:
            groups: ['order','orderLine']

        productDuringOrderPriceUser:
            groups: ['order','orderLine']

        productDuringOrderPriceAdmin:
            groups: ['order','orderLine']

        productDuringOrderRealPrice:
            groups: []






