AppBundle\Entity\MoneyFlow:
    exclusion_policy: NONE
    properties:
        id:
            groups: ['moneyFlow','userAccount']

        value:
            groups: ['moneyFlow'

        debitUserAccount:
            groups: ['moneyFlow']

        creditUserAccount:
            groups: ['moneyFlow']

        description:
            groups: ['moneyFlow']

        createdAt:
            groups: ['moneyFlow']
        isCancelled:
            groups: ['userAccount']
    virtual_properties:
        getDebitUserDetails:
            groups: ['userAccount']

        getCreditUserDetails:
            groups: ['userAccount']



