AppBundle\Entity\Product:
    exclusion_policy: NONE
    properties:
        id:
            groups: ['product','productCategory', 'order','orderLine','userAccount']
        name:
            groups: ['product','order', 'orderline','productCategory']

        barcode:
            groups: ['product','order','orderline','productCategory']

        amountAvailableInStock:
            groups: ['product']

        productCategory:
            groups:  ['product','order']

        productPromotionAdmin:
              groups:  ['product','productCategory','order','orderline']

        productPromotionUser:
              groups:  ['product','productCategory','order','orderline']

        productRealPrice:
              groups:  ['product']

        productAlcoolPercentage:
              groups:  ['product']

        productQuantityCl:
              groups:  ['product']

        isComplete:
              groups:  ['product']

        missingInfo:
              groups:  ['product']
    virtual_properties:
        getPriceWithPromotionAdmin:
             groups:  ['product','productCategory','order','orderline']

        getPriceWithPromotionUser:
                     groups:  ['product','productCategory','order','orderline']


