AppBundle\Entity\Order:
    exclusion_policy: NONE
    properties:
        id:
            groups: ['order','orderLine','userAccount']

        orderLines:
            groups: ['order']

        customerUserAccount:
            groups: ['order']

        registerAccount:
            groups: ['order']

        isPaidCash:
            groups: ['order','userAccount']

        createdAt:
            groups: ['order','userAccount']

        isCancelled:
            groups: ['order','userAccount']

        isOrderedByCustomer:
            groups: ['order','userAccount']

    virtual_properties:
            getOrderPrice:
                groups: ['order','userAccount']

            getCustomerDetails:
                groups: ['order','userAccount']


