AppBundle\Entity\Order:
    exclusion_policy: NONE
    properties:
        id:
            groups: ['order','orderLine','userAccount']

        orderLines:
            groups: ['order']

        customerUserAccount:
            groups: ['order']

        registerAccount:
            groups: ['order']

        isPaidCash:
            groups: ['order']

        createdAt:
            groups: ['order']

        isCancelled:
            groups: ['order']
        isOrderedByCustomer:
            groups: ['order']

    virtual_properties:
            getOrderPrice:
                groups: ['order']

            getCustomerDetails:
                groups: ['order']


