AppBundle\Entity\Product:
    exclusion_policy: NONE
    properties:
        id:
            groups: ['product','productCategory', 'order','orderLine','userAccount']
        name:
            groups: ['product',]

        barcode:
            groups: ['product',]

        amountAvailableInStock:
            groups: ['product']

        productCategory:
            groups:  ['product']


