AppBundle\Entity\Product:
    exclusion_policy: NONE
    properties:
        id:
            groups: ['product','productCategory', 'order','orderLine','userAccount']
        name:
            groups: ['product','order', 'orderline','productCategory']

        barcode:
            groups: ['product','order','orderline']

        amountAvailableInStock:
            groups: ['product']

        productCategory:
            groups:  ['product']

        productPromotion:
              groups:  ['product','productCategory','order','orderline']

    virtual_properties:
        getPriceWithPromotion:
             groups:  ['product','productCategory','order','orderline']


