<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UserAccount extends \AppBundle\Entity\UserAccount implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\UserAccount' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\UserAccount' . "\0" . 'type', '' . "\0" . 'AppBundle\\Entity\\UserAccount' . "\0" . 'moneyBalance', '' . "\0" . 'AppBundle\\Entity\\UserAccount' . "\0" . 'user', '' . "\0" . 'AppBundle\\Entity\\UserAccount' . "\0" . 'orders', '' . "\0" . 'AppBundle\\Entity\\UserAccount' . "\0" . 'registerOrders', '' . "\0" . 'AppBundle\\Entity\\UserAccount' . "\0" . 'positiveMoneyFlows', '' . "\0" . 'AppBundle\\Entity\\UserAccount' . "\0" . 'negativeMoneyFlows', '' . "\0" . 'AppBundle\\Entity\\UserAccount' . "\0" . 'moneyLimit', '' . "\0" . 'AppBundle\\Entity\\UserAccount' . "\0" . 'creditToAllowMax', '' . "\0" . 'AppBundle\\Entity\\UserAccount' . "\0" . 'creditAllowed'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\UserAccount' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\UserAccount' . "\0" . 'type', '' . "\0" . 'AppBundle\\Entity\\UserAccount' . "\0" . 'moneyBalance', '' . "\0" . 'AppBundle\\Entity\\UserAccount' . "\0" . 'user', '' . "\0" . 'AppBundle\\Entity\\UserAccount' . "\0" . 'orders', '' . "\0" . 'AppBundle\\Entity\\UserAccount' . "\0" . 'registerOrders', '' . "\0" . 'AppBundle\\Entity\\UserAccount' . "\0" . 'positiveMoneyFlows', '' . "\0" . 'AppBundle\\Entity\\UserAccount' . "\0" . 'negativeMoneyFlows', '' . "\0" . 'AppBundle\\Entity\\UserAccount' . "\0" . 'moneyLimit', '' . "\0" . 'AppBundle\\Entity\\UserAccount' . "\0" . 'creditToAllowMax', '' . "\0" . 'AppBundle\\Entity\\UserAccount' . "\0" . 'creditAllowed'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UserAccount $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoneyBalance($moneyBalance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoneyBalance', [$moneyBalance]);

        return parent::setMoneyBalance($moneyBalance);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoneyBalance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoneyBalance', []);

        return parent::getMoneyBalance();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrders', []);

        return parent::getOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrders($orders)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrders', [$orders]);

        return parent::setOrders($orders);
    }

    /**
     * {@inheritDoc}
     */
    public function getPositiveMoneyFlows()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPositiveMoneyFlows', []);

        return parent::getPositiveMoneyFlows();
    }

    /**
     * {@inheritDoc}
     */
    public function setPositiveMoneyFlows($positiveMoneyFlows)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPositiveMoneyFlows', [$positiveMoneyFlows]);

        return parent::setPositiveMoneyFlows($positiveMoneyFlows);
    }

    /**
     * {@inheritDoc}
     */
    public function getNegativeMoneyFlows()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNegativeMoneyFlows', []);

        return parent::getNegativeMoneyFlows();
    }

    /**
     * {@inheritDoc}
     */
    public function setNegativeMoneyFlows($negativeMoneyFlows)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNegativeMoneyFlows', [$negativeMoneyFlows]);

        return parent::setNegativeMoneyFlows($negativeMoneyFlows);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegisterOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegisterOrders', []);

        return parent::getRegisterOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function setCashRegisterOrders($registerOrders)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCashRegisterOrders', [$registerOrders]);

        return parent::setCashRegisterOrders($registerOrders);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreditToAllowMax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreditToAllowMax', []);

        return parent::getCreditToAllowMax();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreditToAllowMax($creditToAllowMax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreditToAllowMax', [$creditToAllowMax]);

        return parent::setCreditToAllowMax($creditToAllowMax);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreditAllowed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreditAllowed', []);

        return parent::getCreditAllowed();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreditAllowed($creditAllowed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreditAllowed', [$creditAllowed]);

        return parent::setCreditAllowed($creditAllowed);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoneyLimit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoneyLimit', []);

        return parent::getMoneyLimit();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoneyLimit($moneyLimit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoneyLimit', [$moneyLimit]);

        return parent::setMoneyLimit($moneyLimit);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailableBalance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvailableBalance', []);

        return parent::getAvailableBalance();
    }

}
